# Generated by Django 5.2.5 on 2025-12-05 08:42

import eventyay.base.models.event
from django.db import migrations, models


LANGUAGE_CHOICES = [
    ('en', 'English'),
    ('de', 'German'),
    ('de-formal', 'German (formal)'),
    ('ar', 'Arabic'),
    ('bg', 'Bulgarian'),
    ('ca', 'Catalan'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('el', 'Greek'),
    ('es', 'Spanish'),
    ('fa-ir', 'Persian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('hu', 'Hungarian'),
    ('id', 'Indonesian'),
    ('it', 'Italian'),
    ('ja-jp', 'Japanese'),
    ('ko', 'Korean'),
    ('lv', 'Latvian'),
    ('ms', 'Malay'),
    ('nb-no', 'Norwegian Bokmål'),
    ('nl', 'Dutch'),
    ('nl-informal', 'Dutch (informal)'),
    ('pl', 'Polish'),
    ('pl-informal', 'Polish (informal)'),
    ('pt-br', 'Brazilian Portuguese'),
    ('pt-pt', 'Portuguese (Portugal)'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('si', 'Sinhala'),
    ('sl', 'Slovenian'),
    ('sv', 'Swedish'),
    ('sw', 'Swahili'),
    ('th', 'Thai'),
    ('tr', 'Turkish'),
    ('uk', 'Ukrainian'),
    ('vi', 'Vietnamese'),
    ('zh-hans', 'Chinese (Simplified)'),
    ('zh-hant', 'Chinese (Traditional)'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, help_text='This image appears at the top of all event pages, replacing the default color or pattern. It is center-aligned and not stretched, ensuring the middle part remains visible on smaller screens. We recommend an image at least 1170 px wide and 120 px in height for best results.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=LANGUAGE_CHOICES, default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='When you upload a logo, the event name and date will not appear in the header. The logo scales to 140 px in height while maintaining aspect ratio.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Yes/No'), ('file', 'File upload'), ('choices', 'Radio button (Choose one option)'), ('multiple_choice', 'Checkbox (Choose one or several options)')], default='string', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=LANGUAGE_CHOICES, default='en', max_length=50, verbose_name='Language'),
        ),
    ]
