# Generated by Django 5.2.5 on 2025-11-07 16:37

import django.contrib.postgres.fields
import django.db.models.deletion
import i18nfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composing_for', models.CharField(choices=[('attendees', 'Attendees'), ('teams', 'Teams')], default='attendees', max_length=20)),
                ('subject', i18nfield.fields.I18nTextField(blank=True, null=True)),
                ('message', i18nfield.fields.I18nTextField(blank=True, null=True)),
                ('reply_to', models.CharField(blank=True, default='', max_length=100)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, default='', max_length=16)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_queue', to='base.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueueFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(blank=True, choices=[('orders', 'Orders'), ('attendees', 'Attendees'), ('both', 'Both')], default='orders', max_length=10)),
                ('order_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('checkin_lists', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('has_filter_checkins', models.BooleanField(default=False)),
                ('not_checked_in', models.BooleanField(default=False)),
                ('subevent', models.IntegerField(blank=True, null=True)),
                ('subevents_from', models.DateTimeField(blank=True, null=True)),
                ('subevents_to', models.DateTimeField(blank=True, null=True)),
                ('order_created_from', models.DateTimeField(blank=True, null=True)),
                ('order_created_to', models.DateTimeField(blank=True, null=True)),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('teams', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filters_data', to='sendmail.emailqueue')),
            ],
        ),
        migrations.CreateModel(
            name='EmailQueueToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('team', models.IntegerField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sendmail.emailqueue')),
            ],
            options={
                'unique_together': {('mail', 'email')},
            },
        ),
    ]
